# Generated by Django 5.1.1 on 2024-09-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('Codigo_Cargo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
