# Generated by Django 5.1.1 on 2024-09-21 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('Codigo_Empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Apellido', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Codigo_Cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Cargos.cargos')),
            ],
        ),
    ]
