# Generated by Django 5.1.1 on 2024-09-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('Codigo_Servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
